-- CREATING DATA BASE

CREATE DATABASE CONTACT_MANAGER

USE CONTACT_MANAGER

-- TABLES

CREATE TABLE CONTACTS (	
	CONTACTID INT IDENTITY PRIMARY KEY,
	CONTACT_NAME NVARCHAR(50),
	TELEPHONE NVARCHAR(15),
	EMAIL NVARCHAR(50),
	DATEADDED DATE
);

-- PROCEDURES TO GET, FIND, SAVE, EDIT AND DELETE A CONTACT 

CREATE PROCEDURE GET_ALL_CONTACTS AS BEGIN SELECT * FROM CONTACTS END

CREATE PROCEDURE FIND_CONTACT_ID (@CONTACTID INT) AS BEGIN SELECT * FROM CONTACTS WHERE CONTACTID = @CONTACTID END

CREATE PROCEDURE SAVE_CONTACT (@CONTACT_NAME NVARCHAR(50), @TELEPHONE NVARCHAR(15), @EMAIL NVARCHAR(50), @DATEADDED DATE) 

	AS BEGIN 
		INSERT INTO CONTACTS (CONTACT_NAME, TELEPHONE, EMAIL, DATEADDED) 
			VALUES (@CONTACT_NAME, @TELEPHONE, @EMAIL, @DATEADDED) 
	END

CREATE PROCEDURE EDIT_CONTACT (@CONTACTID INT, @CONTACT_NAME NVARCHAR(50), @TELEPHONE NVARCHAR(15), @EMAIL NVARCHAR(50), @DATEADDED DATE) 

	AS BEGIN 
		UPDATE CONTACTS SET CONTACT_NAME = @CONTACT_NAME, TELEPHONE = @TELEPHONE, EMAIL = @EMAIL, DATEADDED = @DATEADDED WHERE CONTACTID = @CONTACTID
	END

CREATE PROCEDURE DELETE_CONTACT (@CONTACTID INT) AS BEGIN DELETE FROM CONTACTS WHERE CONTACTID = @CONTACTID END

-- Testing

SELECT * FROM CONTACTS;